# Generated by Django 4.2.21 on 2025-06-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feedback_updated_at_alter_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='selected_option',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='explanation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
        migrations.AlterUniqueTogether(
            name='explanation',
            unique_together={('question', 'selected_option')},
        ),
        migrations.CreateModel(
            name='ImproveSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_improve', models.BooleanField(default=False)),
                ('suggestion', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
    ]
