# Generated by Django 4.2.21 on 2025-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_explanation_selected_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptlog',
            name='wrong_option',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='gptlog',
            unique_together={('original_question', 'wrong_option')},
        ),
        migrations.RemoveField(
            model_name='gptlog',
            name='created_at',
        ),
    ]
