# Generated by Django 4.2.21 on 2025-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_gptlog_wrong_option_alter_gptlog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptlog',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
