# Generated by Django 4.2.21 on 2025-06-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_gptlog_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvesuggestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='improvesuggestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improve_suggestions', to='core.question'),
        ),
        migrations.AlterField(
            model_name='improvesuggestion',
            name='suggestion',
            field=models.TextField(blank=True),
        ),
    ]
